# Generated by Django 4.0.2 on 2023-09-22 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(default='No Name', help_text='Customer name', max_length=50)),
                ('email', models.EmailField(blank=True, default='ex@2xample.com', help_text='Customer email', max_length=50)),
                ('phone', models.CharField(default='09122222222', help_text='Customer phone number', max_length=16, unique=True)),
                ('password', models.CharField(default='111', help_text='Customer password', max_length=32)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('national_code', models.CharField(help_text='Customer national code', max_length=10)),
                ('score', models.IntegerField(blank=True, default=0, editable=False, help_text='Customer score')),
                ('status', models.CharField(choices=[('UA', 'usual'), ('DT', 'deleted'), ('CM', 'complete'), ('PR', 'premium')], default='UA', max_length=2)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('modify_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_delete', models.BooleanField(default=False, editable=False)),
                ('country', models.CharField(default='Country', help_text='Country name', max_length=50)),
                ('city', models.CharField(default='City', help_text='City name', max_length=50)),
                ('street', models.CharField(default='Address', help_text='Full Address', max_length=200)),
                ('zipcode', models.CharField(blank=True, default='1111111111', help_text='Zip Code', max_length=11, null=True)),
                ('count', models.IntegerField(default=0, editable=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
